export const JWT_VERIFICATION_TOKEN_SECRET = 'JWT_VERIFICATION_TOKEN_SECRET';
export const JWT_VERIFICATION_TOKEN_EXPIRATION_TIME = 'JWT_VERIFICATION_TOKEN_EXPIRATION_TIME';
export const EMAIL_CONFIRMATION_URL = 'EMAIL_CONFIRMATION_URL';

export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME';
export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME';
